export const lightTheme = {
  name: "light",
  primaryColor: "#79A6DC", 
  primaryLightest: "#EBF2FA",
  primaryLighter: "#B8D3F2",
  primaryDarker: "#5686C4",
  secondaryColor: "#63C5B9", 
  secondaryLightest: "#E0F5F3",
  secondaryLighter: "#A0DCD5",
  secondaryDarker: "#43A89C",
  pageBackground: "#F8F9FA",
  cardBackgroundColor: "#FFFFFF",
  cardBorderColor: "#E9ECEF",
  subtleTextColor: "#ADB5BD",
  textColor: "#495057",
  headingColor: "#212529",
  successStoryBg: "#F5EFE6",
  communityElementBg: "#D8D8F6",
  expertTipBg: "#DFF2F0",
  ctaColor: "#FF8C69", 
  achievementColor: "#FFD700", 
  sleepExcellent: "#77DD77",
  sleepGood: "#A9D086",
  sleepFair: "#FFB347",
  sleepPoor: "#FF6961",
  fontFamilyHeadings: "\"Nunito Sans\", sans-serif",
  fontFamilyBody: "\"Open Sans\", sans-serif",
  navButtonHoverBg: "rgba(255, 255, 255, 0.2)",
  navButtonActiveBg: "rgba(255, 255, 255, 0.3)",
  buttonHoverScale: 1.05,
  buttonTapScale: 0.95,
};

export const darkTheme = {
  name: "dark",
  primaryColor: "#5C6BC0", 
  primaryDarkerBg: "#3949AB",
  primaryLighterAccent: "#7986CB",
  primaryLightestHighlight: "#C5CAE9",
  secondaryColor: "#8E7CC3", 
  secondaryDarkerBg: "#4A407D",
  secondaryLighterAccent: "#B3A0D9",
  secondaryLightestHighlight: "#DCD5F0",
  pageBackground: "#1A1D22",
  cardBackgroundColor: "#2C313A",
  cardBorderColor: "#4A407D", 
  subtleTextColor: "#6C757D",
  textColor: "#CED4DA",
  headingColor: "#F8F9FA",
  successStoryBg: "#423B32", 
  communityElementBg: "#4B4B7D", 
  expertTipBg: "#365C58", 
  ctaColor: "#FFA07A", 
  achievementColor: "#FFDF33", 
  sleepExcellent: "#77DD77",
  sleepGood: "#A9D086",
  sleepFair: "#FFB347",
  sleepPoor: "#FF6961",
  fontFamilyHeadings: "\"Nunito Sans\", sans-serif",
  fontFamilyBody: "\"Open Sans\", sans-serif",
  navButtonHoverBg: "rgba(0, 0, 0, 0.2)",
  navButtonActiveBg: "rgba(0, 0, 0, 0.3)",
  buttonHoverScale: 1.05,
  buttonTapScale: 0.95,
};
